services:
  db:
    image: postgres:14
    container_name: devquest-db
    ports:
      - "5432:5432"
    networks:
      - devquest-network
    environment:
      POSTGRES_USER: bagrielz
      POSTGRES_PASSWORD: password
      POSTGRES_DB: devquest
    volumes:
      - postgres_devquest:/var/lib/postgresql/data

volumes:
  postgres_devquest:

networks:
  devquest-network:
    driver: bridge